---
name: _rwstauner_run_control
version: 0.0.0
files: []
private: true
preferGlobal: true

peerDependencies:
  # Let me play with Backbone in a terminal repl.
  backbone: x

  # cli app
  bible: x

  bower: x

  coffee-script: x
  coffeelint: x

  # js utilities
  js-beautify: x
  jshint: x
  jslint: x
  jsonlint: x

  # lesscss
  #http://registry.npmjs.org/less/-/less-1.6.3.tgz: ~
  less: '>=1.7.0'

  lodash: x
  # Customize lodash builds.
  lodash-cli: x

  node-static: x

  phantomjs: x

  requirejs: '>=2.1.2'
  # require.js "text!" plugin
  text: x

  underscore: '>=1.6.0'
  uglify-js: '>=2'

  yo: x

# Define repository to silence npm warning.
repository:
  type: git
  url: http://github.com/rwstauner/run_control
